name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - id: action-security-banner
      run: echo '::warning title=fix yo shiz::this is action is disabled due to security violations; gtfo'
      shell: bash
    - id: random-number-generator
      run: echo "NONE random-number=$(echo $RANDOM)"
      shell: bash
